CREATE TABLE role(
    role_id INTEGER NOT NULL UNIQUE ,
    name VARCHAR(122) NOT NULL UNIQUE
);

INSERT IGNORE INTO role (role_id, name) VALUES (1, 'ADMIN');
INSERT IGNORE INTO role (role_id, name) VALUES (2, 'MERCHANT_PREMIUM');
INSERT IGNORE INTO role (role_id, name) VALUES (3, 'MERCHANTS');
INSERT IGNORE INTO role (role_id, name) VALUES (4, 'CUSTOMER');