CREATE TABLE role (
      role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(255) NOT NULL UNIQUE
);

INSERT INTO role (role_id ,name) VALUES (1, 'ROLE_ADMIN');
INSERT INTO role (role_id ,name) VALUES (2,'MERCHANT_PREMIUM');
INSERT INTO role (role_id ,name) VALUES (3,'MERCHANT');
INSERT INTO role (role_id ,name) VALUES (4,'VIP');
INSERT INTO role (role_id ,name) VALUES (5,'BASIC');