CREATE TABLE permission (
    permission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, permission_id),
    FOREIGN KEY (role_id) REFERENCES role (role_id),
    FOREIGN KEY (permission_id) REFERENCES permission (permission_id)
);

INSERT INTO permission (name) VALUES
    ('ORDER:CREATE'),
    ('ACCOUNT:EDIT_OWN'),
    ('ACCOUNT:DELETE_OWN'),
    ('PRODUCT:CREATE'),
    ('PRODUCT:EDIT'),
    ('ORDER:DELETE');

INSERT INTO role_permissions (role_id, permission_id)
SELECT
    (SELECT role_id FROM role WHERE name = 'ROLE_CUSTOMER'),
    p.permission_id
FROM permission p
WHERE p.name IN ('ORDER:CREATE', 'ACCOUNT:EDIT_OWN', 'ACCOUNT:DELETE_OWN');

INSERT INTO role_permissions (role_id, permission_id)
SELECT
    (SELECT role_id FROM role WHERE name = 'ROLE_MERCHANT'),
    p.permission_id
FROM permission p
WHERE p.name IN ('PRODUCT:CREATE', 'PRODUCT:EDIT', 'ORDER:DELETE', 'ACCOUNT:EDIT_OWN');

INSERT INTO role_permissions (role_id, permission_id)
SELECT
    (SELECT role_id FROM role WHERE name = 'ROLE_ADMIN'),
    p.permission_id
FROM permission p;